### ISSUE TITLE
Tracking issue for Field Capture Work

### ISSUE THREAD

**Issue by shawn-hurley** [konveyor/windup-shim#54]
- [x] https://github.com/konveyor/windup-shim/issues/52
- [x] https://github.com/konveyor/windup-shim/issues/51
- [x] https://github.com/konveyor/windup-shim/issues/50
- [x] https://github.com/konveyor/windup-shim/issues/49
- [x] https://github.com/konveyor/windup-shim/issues/48
- [x] https://github.com/konveyor/windup-shim/issues/53

**Comment by shawn-hurley** [comment]
All tasks completed, closing.
